/*
* ===========================================================================
*
*                            PUBLIC DOMAIN NOTICE
*               National Center for Biotechnology Information
*
*  This software/database is a "United States Government Work" under the
*  terms of the United States Copyright Act.  It was written as part of
*  the author's official duties as a United States Government employee and
*  thus cannot be copyrighted.  This software/database is freely available
*  to the public for use. The National Library of Medicine and the U.S.
*  Government have not placed any restriction on its use or reproduction.
*
*  Although all reasonable efforts have been taken to ensure the accuracy
*  and reliability of the software and data, the NLM and the U.S.
*  Government do not and cannot warrant the performance or results that
*  may be obtained by using this software or data. The NLM and the U.S.
*  Government disclaim all warranties, express or implied, including
*  warranties of performance, merchantability or fitness for any particular
*  purpose.
*
*  Please cite the author in any work or product based on this material.
*
* ===========================================================================
*
*  FileName: CParmOsiris.cpp
*  Author:   this file was generated by CParmOsiris.pl
*            a perl script written by Douglas Hoffman
*
*/
#include "mainApp.h"
#include "CParmOsiris.h"
#include "CLabSettings.h"
#include "CVolumes.h"
#include "nwx/nwxFileUtil.h"
#include <wx/filename.h>
#include <wx/utils.h>


CParmOsiris *CParmOsiris::g_p(NULL); // global pointer
CParmOsiris::CCleanupGlobal CParmOsiris::g_xxx;

void CParmOsiris::_Init()
{
  if(m_sFileName.IsEmpty())
  {
    m_sFileName = mainApp::GetConfig()->GetConfigPath();
    m_sFileName += _T("osiris.xml");
  }
  m_bModified = false;
  m_bAutoSave = false;
  RegisterAll(true);
  if(!(  wxFileName::FileExists(m_sFileName) && Load()  ))
  {
    SetDefaults();
  }
}


CParmOsiris &CParmOsiris::operator =(const CParmOsiris &x)
{
#define CP(elem) elem = x.elem

  CP(m_sFileName);

  // begin generated copy

  CP(m_sLastExportXSLsearch);
  CP(m_sLastExportDirectory);
  CP(m_sInputDirectory);
  CP(m_sOutputDirectory);

  //   m_sKitName is obsolete, use volume name

  CP(m_sKitName);
  CP(m_sVolumeName);
  CP(m_sLsName);
  CP(m_nMinRFU_Sample);
  CP(m_nMinRFU_Interlocus);
  CP(m_nMinRFU_ILS);
  CP(m_nMinRFU_Ladder);
  CP(m_nMinLadderInterlocusRFU);
  CP(m_nSampleDetectionThreshold);
  CP(m_sAnalysisOverride);
  CP(m_bTimeStampSubDir);
  CP(m_bDataAnalyzed);

  //  CMF settings

  CP(m_sCMFsourceLab);
  CP(m_sCMFdestLab);
  CP(m_sCMFdefaultSample);
  CP(m_sCMFbatchFormat);
  CP(m_sCMFuserID);
  CP(m_bCMFviewLocation);

  //  PNG Export Settings

  CP(m_dPNGwidth);
  CP(m_dPNGheight);
  CP(m_nPNGunits);
  CP(m_nPNGusage);
  CP(m_bPNGviewLocation);
  CP(m_nShowAlerts);
  CP(m_bShowPreview);
  CP(m_bHideGraphicToolbar);
  CP(m_bHideGraphicScrollbar);
  CP(m_bHideTextToolbar);
  CP(m_bStartupMRU);
  CP(m_bCheckBeforeExit);
  CP(m_bWarnOnHistory);
  CP(m_dZoomLocusMargin);

  //  grid

  CP(m_nTableDisplayPeak);
  CP(m_nTableSortBy);
  CP(m_bTableControlsAtTop);
  CP(m_nTableShowSampleDisplayNames);

  //  preview settings

  CP(m_bPreviewDataAnalyzed);
  CP(m_bPreviewDataRaw);
  CP(m_bPreviewDataLadder);
  CP(m_bPreviewDataBaseline);
  CP(m_bPreviewShowILS);
  CP(m_bPreviewShowRFU);
  CP(m_bPreviewShowLadderLabels);
  CP(m_nPreviewShowArtifact);

  //  plot settings

  CP(m_bPlotDataAnalyzed);
  CP(m_bPlotDataRaw);
  CP(m_bPlotDataLadder);
  CP(m_bPlotDataBaseline);
  CP(m_bPlotShowILS);
  CP(m_bPlotShowRFU);
  CP(m_bPlotShowLadderLabels);
  CP(m_bPlotResizable);
  CP(m_nPlotMinHeight);
  CP(m_nPlotShowArtifact);
  CP(m_nPlotDisplayPeak);
  CP(m_nPlotMaxLadderLabels);

  //  XSLT saved parameter info

  CP(m_sLastXSLInputFileDir);


  // end generated copy

  CP(m_bModified);
  m_bAutoSave = false;
  CP(m_gridAttr);

#undef CP
  return *this;
}

bool CParmOsiris::IsEqual(const CParmOsiris &x) const
{
#define CP(elem) else if(elem != x.elem) { bRtn = false; }
  bool bRtn = true;
  if(0) {}
  // begin generated compare

  CP(m_sLastExportXSLsearch)
  CP(m_sLastExportDirectory)
  CP(m_sInputDirectory)
  CP(m_sOutputDirectory)

  //   m_sKitName is obsolete, use volume name

  CP(m_sKitName)
  CP(m_sVolumeName)
  CP(m_sLsName)
  CP(m_nMinRFU_Sample)
  CP(m_nMinRFU_Interlocus)
  CP(m_nMinRFU_ILS)
  CP(m_nMinRFU_Ladder)
  CP(m_nMinLadderInterlocusRFU)
  CP(m_nSampleDetectionThreshold)
  CP(m_sAnalysisOverride)
  CP(m_bTimeStampSubDir)
  CP(m_bDataAnalyzed)

  //  CMF settings

  CP(m_sCMFsourceLab)
  CP(m_sCMFdestLab)
  CP(m_sCMFdefaultSample)
  CP(m_sCMFbatchFormat)
  CP(m_sCMFuserID)
  CP(m_bCMFviewLocation)

  //  PNG Export Settings

  CP(m_dPNGwidth)
  CP(m_dPNGheight)
  CP(m_nPNGunits)
  CP(m_nPNGusage)
  CP(m_bPNGviewLocation)
  CP(m_nShowAlerts)
  CP(m_bShowPreview)
  CP(m_bHideGraphicToolbar)
  CP(m_bHideGraphicScrollbar)
  CP(m_bHideTextToolbar)
  CP(m_bStartupMRU)
  CP(m_bCheckBeforeExit)
  CP(m_bWarnOnHistory)
  CP(m_dZoomLocusMargin)

  //  grid

  CP(m_nTableDisplayPeak)
  CP(m_nTableSortBy)
  CP(m_bTableControlsAtTop)
  CP(m_nTableShowSampleDisplayNames)

  //  preview settings

  CP(m_bPreviewDataAnalyzed)
  CP(m_bPreviewDataRaw)
  CP(m_bPreviewDataLadder)
  CP(m_bPreviewDataBaseline)
  CP(m_bPreviewShowILS)
  CP(m_bPreviewShowRFU)
  CP(m_bPreviewShowLadderLabels)
  CP(m_nPreviewShowArtifact)

  //  plot settings

  CP(m_bPlotDataAnalyzed)
  CP(m_bPlotDataRaw)
  CP(m_bPlotDataLadder)
  CP(m_bPlotDataBaseline)
  CP(m_bPlotShowILS)
  CP(m_bPlotShowRFU)
  CP(m_bPlotShowLadderLabels)
  CP(m_bPlotResizable)
  CP(m_nPlotMinHeight)
  CP(m_nPlotShowArtifact)
  CP(m_nPlotDisplayPeak)
  CP(m_nPlotMaxLadderLabels)

  //  XSLT saved parameter info

  CP(m_sLastXSLInputFileDir)


  // end generated compare


  CP(m_gridAttr)
//  CP(m_bModified)
//  CP(m_bAutoSave)

#undef CP
  return bRtn;
}


void CParmOsiris::RegisterAll(bool bInConstructor)
{
  if(bInConstructor)
  {
    m_ioDefaultSample.SetDefault(
      _T(CLabNameStrings::DEFAULT_SPECIMEN_CATEGORY));
    m_ioBatchFormat.SetDefault(DEFAULT_BATCH_FORMAT);
    m_ioUintViewPlotArtifact.SetDefault(15);
    m_ioUint1.SetDefault(1);
    m_ioInt_1.SetDefault(-1);
  }

  // begin generated register

  RegisterWxString(_T("LastExportXSLsearch"), &m_sLastExportXSLsearch);
  RegisterWxString(_T("LastExportDirectory"), &m_sLastExportDirectory);
  RegisterWxString(_T("inputDirectory"), &m_sInputDirectory);
  RegisterWxString(_T("outputDirectory"), &m_sOutputDirectory);

  //   m_sKitName is obsolete, use volume name

  RegisterWxString(_T("kit"), &m_sKitName);
  RegisterWxString(_T("volume"), &m_sVolumeName);
  RegisterWxString(_T("ls"), &m_sLsName);
  RegisterInt(_T("minRFUsample"), &m_nMinRFU_Sample);
  RegisterInt(_T("minRFUinterlocus"), &m_nMinRFU_Interlocus);
  RegisterInt(_T("minRFUILS"), &m_nMinRFU_ILS);
  RegisterInt(_T("minRFUladder"), &m_nMinRFU_Ladder);
  RegisterInt(_T("minRFUladderInterlocus"), &m_nMinLadderInterlocusRFU);
  RegisterInt(_T("minRFUsampleDetection"), &m_nSampleDetectionThreshold);
  RegisterWxString(_T("AnalysisOverride"), &m_sAnalysisOverride);
  RegisterBool(_T("TimeStampSubDir"), &m_bTimeStampSubDir);
  RegisterBool(_T("DataAnalyzed"), &m_bDataAnalyzed);

  //  CMF settings

  RegisterWxString(_T("CMFsourceLab"), &m_sCMFsourceLab);
  RegisterWxString(_T("CMFdestLab"), &m_sCMFdestLab);
  Register(_T("CMFdefaultSample"),&m_ioDefaultSample,(void *) &m_sCMFdefaultSample);
  Register(_T("CMFbatchFormat"),&m_ioBatchFormat,(void *) &m_sCMFbatchFormat);
  RegisterWxString(_T("CMFuserID"), &m_sCMFuserID);
  RegisterBool(_T("CMFviewLocation"), &m_bCMFviewLocation);

  //  PNG Export Settings

  RegisterDouble(_T("PNGwidth"), &m_dPNGwidth);
  RegisterDouble(_T("PNGheight"), &m_dPNGheight);
  RegisterInt(_T("PNGunits"), &m_nPNGunits);
  RegisterInt(_T("PNGusage"), &m_nPNGusage);
  RegisterBool(_T("PNGviewLocation"), &m_bPNGviewLocation);
  Register(_T("ShowAlerts"),&m_ioInt_1,(void *) &m_nShowAlerts);
  RegisterBoolTrue(_T("ShowPreview"), &m_bShowPreview);
  RegisterBool(_T("HideGraphicToolbar"), &m_bHideGraphicToolbar);
  RegisterBool(_T("HideGraphicScrollbar"), &m_bHideGraphicScrollbar);
  RegisterBool(_T("HideTextToolbar"), &m_bHideTextToolbar);
  RegisterBoolTrue(_T("StartupMRU"), &m_bStartupMRU);
  RegisterBoolTrue(_T("CheckBeforeExit"), &m_bCheckBeforeExit);
  RegisterBoolTrue(_T("WarnOnHistory"), &m_bWarnOnHistory);
  RegisterDouble(_T("ZoomLocusMargin"), &m_dZoomLocusMargin);

  //  grid

  RegisterInt(_T("TableDisplayPeak"), &m_nTableDisplayPeak);
  RegisterInt(_T("TableSortBy"), &m_nTableSortBy);
  RegisterBoolTrue(_T("TableControlsAtTop"), &m_bTableControlsAtTop);
  RegisterInt(_T("TableShowSampleDisplayNames"), &m_nTableShowSampleDisplayNames);

  //  preview settings

  RegisterBoolTrue(_T("PreviewDataAnalyzed"), &m_bPreviewDataAnalyzed);
  RegisterBool(_T("PreviewDataRaw"), &m_bPreviewDataRaw);
  RegisterBool(_T("PreviewDataLadder"), &m_bPreviewDataLadder);
  RegisterBool(_T("PreviewDataBaseline"), &m_bPreviewDataBaseline);
  RegisterBool(_T("PreviewShowILS"), &m_bPreviewShowILS);
  RegisterBool(_T("PreviewShowRFU"), &m_bPreviewShowRFU);
  RegisterBool(_T("PreviewShowLadderLabels"), &m_bPreviewShowLadderLabels);
  Register(_T("PreviewArtifact"),&m_ioUintViewPlotArtifact,(void *) &m_nPreviewShowArtifact);

  //  plot settings

  RegisterBoolTrue(_T("PlotDataAnalyzed"), &m_bPlotDataAnalyzed);
  RegisterBool(_T("PlotDataRaw"), &m_bPlotDataRaw);
  RegisterBool(_T("PlotDataLadder"), &m_bPlotDataLadder);
  RegisterBool(_T("PlotDataBaseline"), &m_bPlotDataBaseline);
  RegisterBool(_T("PlotShowILS"), &m_bPlotShowILS);
  RegisterBool(_T("PlotShowRFU"), &m_bPlotShowRFU);
  RegisterBool(_T("PlotShowLadderLabels"), &m_bPlotShowLadderLabels);
  RegisterBool(_T("PlotResizable"), &m_bPlotResizable);
  Register(_T("PlotMinHeight"),&m_ioInt_1,(void *) &m_nPlotMinHeight);
  Register(_T("PlotShowArtifact"),&m_ioUintViewPlotArtifact,(void *) &m_nPlotShowArtifact);
  Register(_T("PlotDisplayPeak"),&m_ioUint1,(void *) &m_nPlotDisplayPeak);
  Register(_T("MaxLadderLabels"),&m_ioInt_1,(void *) &m_nPlotMaxLadderLabels);

  //  XSLT saved parameter info

  RegisterWxString(_T("LastXSLInputFileDir"), &m_sLastXSLInputFileDir);


  // end generated register

  Register(_T("GridColors"),&m_gridAttr);
}

CParmOsiris::~CParmOsiris()
{
  if(m_bAutoSave)
  {
    SaveIfModified();
  }
}

void CParmOsiris::SetDefaults()
{
  ConfigDir *pConfig = mainApp::GetConfig();
  const unsigned int RFU = 150;

  wxString sExe = pConfig->GetExePath();
  wxString sInputDirectory = sExe;
  sInputDirectory += _T("TestAnalysis");
  nwxFileUtil::EndWithSeparator(&sInputDirectory);
  sInputDirectory += _T("Cofiler");

  m_bModified = true;

  // begin generated defaults

  m_sLastExportXSLsearch.Empty();
  m_sLastExportDirectory.Empty();
  m_sInputDirectory = sInputDirectory;
  m_sOutputDirectory = pConfig->GetFilePath();

  //   m_sKitName is obsolete, use volume name

  m_sKitName = _T("Cofiler");
  m_sVolumeName.Empty();
  m_sLsName.Empty();
  m_nMinRFU_Sample = RFU;
  m_nMinRFU_Interlocus = RFU;
  m_nMinRFU_ILS = RFU;
  m_nMinRFU_Ladder = RFU;
  m_nMinLadderInterlocusRFU = -1;
  m_nSampleDetectionThreshold = -1;
  m_sAnalysisOverride.Empty();
  m_bTimeStampSubDir = false;
  m_bDataAnalyzed = false;

  //  CMF settings

  m_sCMFsourceLab.Empty();
  m_sCMFdestLab.Empty();
  m_sCMFdefaultSample.Empty();
  m_sCMFbatchFormat = DEFAULT_BATCH_FORMAT;
  m_sCMFuserID = wxGetUserId();
  m_bCMFviewLocation = false;

  //  PNG Export Settings

  m_dPNGwidth = 1024.0;
  m_dPNGheight = 768.0;
  m_nPNGunits = 0;
  m_nPNGusage = 0;
  m_bPNGviewLocation = false;
  m_nShowAlerts = -1;
  m_bShowPreview = true;
  m_bHideGraphicToolbar = false;
  m_bHideGraphicScrollbar = false;
  m_bHideTextToolbar = false;
  m_bStartupMRU = true;
  m_bCheckBeforeExit = true;
  m_bWarnOnHistory = true;
  m_dZoomLocusMargin = 0.0;

  //  grid

  m_nTableDisplayPeak = 0;
  m_nTableSortBy = 0;
  m_bTableControlsAtTop = true;
  m_nTableShowSampleDisplayNames = 0;

  //  preview settings

  m_bPreviewDataAnalyzed = true;
  m_bPreviewDataRaw = false;
  m_bPreviewDataLadder = false;
  m_bPreviewDataBaseline = false;
  m_bPreviewShowILS = false;
  m_bPreviewShowRFU = false;
  m_bPreviewShowLadderLabels = false;
  m_nPreviewShowArtifact = m_ioUintViewPlotArtifact.GetDefault();

  //  plot settings

  m_bPlotDataAnalyzed = true;
  m_bPlotDataRaw = false;
  m_bPlotDataLadder = false;
  m_bPlotDataBaseline = false;
  m_bPlotShowILS = false;
  m_bPlotShowRFU = false;
  m_bPlotShowLadderLabels = false;
  m_bPlotResizable = false;
  m_nPlotMinHeight = -1;
  m_nPlotShowArtifact = m_ioUintViewPlotArtifact.GetDefault();
  m_nPlotDisplayPeak = 1;
  m_nPlotMaxLadderLabels = -1;

  //  XSLT saved parameter info

  m_sLastXSLInputFileDir.Empty();


  // end generated defaults

  m_gridAttr.SetDefaults();
}
bool CParmOsiris::Save()
{
  bool bRtn = SaveFile(m_sFileName);
  if(!bRtn)
  {
    wxString sError =
      _T("An error occurred when writing OSIRS parameters file:\n");
    sError.Append(m_sFileName);
    wxASSERT_MSG(0,sError);
    mainApp::LogMessage(sError);
  }
  else
  {
    m_bModified = false;
  }
  return bRtn;
}

const wxString CParmOsiris::DEFAULT_BATCH_FORMAT(_T("%Y%m%d_%H%M%S"));
const wxString CParmOsiris::LABEL_VIEW_LOCATION(_T("View File Location"));
const wxString CParmOsiris::LABEL_INPUT(_T("Input Directory "));
const wxString CParmOsiris::LABEL_OUTPUT(_T("Output Directory "));
const wxString CParmOsiris::LABEL_KIT(_T("Kit Name "));
const wxString CParmOsiris::LABEL_VOLUME(_T("Operating Procedure Name "));
const wxString CParmOsiris::LABEL_LS(_T("Internal Lane Standard "));
const wxString CParmOsiris::LABEL_RFU(_T("Minimum RFU "));
const wxString CParmOsiris::LABEL_RFU_SAMPLE(_T("Sample: "));
const wxString CParmOsiris::LABEL_RFU_ILS(_T("ILS: "));
const wxString CParmOsiris::LABEL_RFU_LADDER(_T("Ladder: "));
const wxString CParmOsiris::LABEL_RFU_INTERLOCUS(_T("Interlocus: "));
const wxString CParmOsiris::LABEL_DATA(_T("Data "));
const wxString CParmOsiris::LABEL_DATA_RAW(_T("Raw  "));
const wxString CParmOsiris::LABEL_DATA_ANALYZED(_T("Analyzed"));
const wxString CParmOsiris::LABEL_ANALYSIS(_T("Analysis: "));
const wxString CParmOsiris::LABEL_DETECTION(_T("Detection: "));
const wxString CParmOsiris::LABEL_INTERLOCUS(_T("Interlocus: "));
const wxString CParmOsiris::ERROR_MSG_INTERLOCUS(_T("Minimum interlocus RFU must be\ngreater than or equal to the minimum RFU"));


