#ifndef __C_PRINT_PARAMETERS_H__
#define __C_PRINT_PARAMETERS_H__

#include "wxIDS.h"

#define PRINT_LABEL_ARTIFACT_NONE ARTIFACT_NONE
#define PRINT_LABEL_ARTIFACT_ALL ARTIFACT_ALL
#define PRINT_LABEL_ARTIFACT_CRITICAL ARTIFACT_CRITICAL

#define PRINT_Y_SCALE_CHANNEL 0
#define PRINT_Y_SCALE_SAMPLE 1
#define PRINT_Y_SCALE_USER 2

#define PRINT_Y_SCALE_NEG_PEAKS 0
#define PRINT_Y_SCALE_NEG_INCLUDE_RFU 1
#define PRINT_Y_SCALE_NEG_ILS 2

#define PRINT_X_SCALE_NO_PRIMER_PEAK 0 
#define PRINT_X_SCALE_ALL_PRIMER_PEAK 1
#define PRINT_X_SCALE_CTRL_PRIMER_PEAK 2
#define PRINT_X_SCALE_USER 3

#define PRINT_TITLE_FILE_NAME 0
#define PRINT_TITLE_SAMPLE_NAME 1

#define PRINT_X_BPS 1
#define PRINT_X_TIME 0

#endif