/*
* ===========================================================================
*
*                            PUBLIC DOMAIN NOTICE                          
*               National Center for Biotechnology Information
*                                                                          
*  This software/database is a "United States Government Work" under the   
*  terms of the United States Copyright Act.  It was written as part of    
*  the author's official duties as a United States Government employee and 
*  thus cannot be copyrighted.  This software/database is freely available 
*  to the public for use. The National Library of Medicine and the U.S.    
*  Government have not placed any restriction on its use or reproduction.  
*                                                                          
*  Although all reasonable efforts have been taken to ensure the accuracy  
*  and reliability of the software and data, the NLM and the U.S.          
*  Government do not and cannot warrant the performance or results that    
*  may be obtained by using this software or data. The NLM and the U.S.    
*  Government disclaim all warranties, express or implied, including       
*  warranties of performance, merchantability or fitness for any particular
*  purpose.                                                                
*                                                                          
*  Please cite the author in any work or product based on this material.   
*
* ===========================================================================
*
*  FileName: nwxShiftBitmaps.h
*  Author:   Douglas Hoffman
*    this file was generated by scrollBitmaps.pl
*
*/
#ifndef __NWX_SHIFT_BITMAPS_H__
#define __NWX_SHIFT_BITMAPS_H__


static const unsigned char shiftLeft[] = {
137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 
0, 0, 0, 6, 0, 0, 0, 13, 8, 6, 0, 0, 0, 138, 11, 31, 
139, 0, 0, 0, 40, 73, 68, 65, 84, 120, 156, 99, 96, 160, 41, 248, 
207, 192, 192, 192, 192, 132, 77, 16, 93, 226, 63, 178, 10, 38, 108, 130, 
200, 18, 140, 184, 36, 176, 74, 98, 117, 21, 21, 1, 0, 111, 221, 5, 
8, 174, 45, 134, 41, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 
130
};


static const unsigned char shiftRight[] = {
137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 
0, 0, 0, 6, 0, 0, 0, 13, 8, 6, 0, 0, 0, 138, 11, 31, 
139, 0, 0, 0, 37, 73, 68, 65, 84, 120, 156, 99, 96, 160, 58, 248, 
143, 46, 192, 132, 75, 146, 9, 77, 225, 127, 92, 18, 112, 73, 108, 18, 
140, 216, 36, 24, 9, 186, 138, 138, 0, 0, 123, 193, 5, 8, 89, 227, 
139, 45, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130
};


static const unsigned char shiftLeftDisabled[] = {
137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 
0, 0, 0, 6, 0, 0, 0, 13, 8, 6, 0, 0, 0, 138, 11, 31, 
139, 0, 0, 0, 46, 73, 68, 65, 84, 120, 156, 99, 96, 160, 29, 88, 
179, 102, 205, 127, 6, 6, 6, 6, 38, 108, 130, 40, 18, 200, 130, 112, 
9, 116, 65, 184, 68, 72, 72, 8, 35, 86, 9, 92, 146, 88, 93, 69, 
69, 0, 0, 101, 25, 17, 20, 73, 150, 120, 23, 0, 0, 0, 0, 73, 
69, 78, 68, 174, 66, 96, 130
};


static const unsigned char shiftRightDisabled[] = {
137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 
0, 0, 0, 6, 0, 0, 0, 13, 8, 6, 0, 0, 0, 138, 11, 31, 
139, 0, 0, 0, 45, 73, 68, 65, 84, 120, 156, 99, 96, 160, 46, 88, 
179, 102, 205, 127, 116, 49, 38, 92, 146, 76, 200, 28, 100, 73, 20, 9, 
100, 73, 12, 137, 144, 144, 16, 70, 12, 9, 152, 32, 94, 87, 81, 17, 
0, 0, 121, 109, 17, 20, 233, 1, 241, 237, 0, 0, 0, 0, 73, 69, 
78, 68, 174, 66, 96, 130
};



#endif
