#!/usr/bin/perl
#
#  convert png files to a c header file, scrollBitmaps.h with binary image data 
#
#
use strict 'vars';
use IO::File;


my $EOL = "\r\n";

sub OpenInFile
{
  my $fnIn = shift;
  my $fn = new IO::File("<${fnIn}");
  $fn || die("Cannot open file ${fnIn}");
  binmode $fn;
  $fn;
}
sub OpenOutFile
{
  my $fnOut = shift;
  my $fn = new IO::File(">${fnOut}");
  $fn || die("Cannot open file ${fnOut}");
  binmode $fn; 
  $fn;
}

sub run
{
  my ($fpIn,$fpOut, $imageName) = @_;
  my $n;
  my $i;
  my $s;
  my $nOrd;
  my $nWritten = 0;
  my $nTotal = 0;
  my $comma = "";
  my $str =
    "${EOL}static const unsigned char ${imageName}[] = {${EOL}";
  while ($n = $fpIn->read($s,4096))
  {
    for($i = 0; $i < $n; $i++)
    {
      $str .= $comma;
      $comma = ", ";
      if($nWritten >= 16)
      {
        $str .= "${EOL}";
        $fpOut->print($str);
        $str = "";
        $nWritten = 0;
      }
      $nOrd = ord(substr($s,$i,1));
      $str .= $nOrd;
      $nWritten++;
      $nTotal++;
    }
  }
  $str .= "${EOL}};${EOL}${EOL}";
  $fpOut->print($str);
  0;
}

my $notice = <<EOF;
/*
* ===========================================================================
*
*                            PUBLIC DOMAIN NOTICE                          
*               National Center for Biotechnology Information
*                                                                          
*  This software/database is a "United States Government Work" under the   
*  terms of the United States Copyright Act.  It was written as part of    
*  the author's official duties as a United States Government employee and 
*  thus cannot be copyrighted.  This software/database is freely available 
*  to the public for use. The National Library of Medicine and the U.S.    
*  Government have not placed any restriction on its use or reproduction.  
*                                                                          
*  Although all reasonable efforts have been taken to ensure the accuracy  
*  and reliability of the software and data, the NLM and the U.S.          
*  Government do not and cannot warrant the performance or results that    
*  may be obtained by using this software or data. The NLM and the U.S.    
*  Government disclaim all warranties, express or implied, including       
*  warranties of performance, merchantability or fitness for any particular
*  purpose.                                                                
*                                                                          
*  Please cite the author in any work or product based on this material.   
*
* ===========================================================================
*
*  FileName: nwxShiftBitmaps.h
*  Author:   Douglas Hoffman
*    this file was generated by scrollBitmaps.pl
*
*/
EOF
my $top = "#ifndef __NWX_SHIFT_BITMAPS_H__${EOL}#define __NWX_SHIFT_BITMAPS_H__${EOL}${EOL}";
my $bottom = "${EOL}${EOL}#endif${EOL}";

my $fOut = OpenOutFile("nwxShiftBitmaps.h");
$fOut->print($notice);
$fOut->print($top);
my @arr = qw/shiftLeft shiftRight shiftLeftDisabled shiftRightDisabled/;
my $name;

for $name (@arr)
{
  print "${name}\n";
  my $fIn = &OpenInFile("${name}.png");
  &run($fIn,$fOut,$name);
}


$fOut->print($bottom);

