copy /-Y "%WXHOME%\build\msw\wx_adv.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_aui.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_base.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_core.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_dbgrid.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_gl.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_html.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_media.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_net.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_odbc.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_qa.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_richtext.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_wxexpat.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_wxjpeg.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_wxpng.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_wxregex.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_wxtiff.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_wxzlib.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_xml.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx_xrc.vcxproj" .
copy /-Y "%WXHOME%\samples\animate\anitest.vcxproj" .
copy /-Y "%WXHOME%\samples\artprov\artprov.vcxproj" .
copy /-Y "%WXHOME%\samples\aui\auidemo.vcxproj" .
copy /-Y "%WXHOME%\samples\calendar\calendar.vcxproj" .
copy /-Y "%WXHOME%\samples\caret\caret.vcxproj" .
copy /-Y "%WXHOME%\samples\checklst\checklst.vcxproj" .
copy /-Y "%WXHOME%\samples\collpane\collpane.vcxproj" .
copy /-Y "%WXHOME%\samples\config\config.vcxproj" .
copy /-Y "%WXHOME%\samples\controls\controls.vcxproj" .
copy /-Y "%WXHOME%\samples\dataview\dataview.vcxproj" .
copy /-Y "%WXHOME%\samples\db\db.vcxproj" .
copy /-Y "%WXHOME%\samples\dialogs\dialogs.vcxproj" .
copy /-Y "%WXHOME%\samples\dialup\dialup.vcxproj" .
copy /-Y "%WXHOME%\samples\dnd\dnd.vcxproj" .
copy /-Y "%WXHOME%\samples\docview\docview.vcxproj" .
copy /-Y "%WXHOME%\samples\docvwmdi\docvwmdi.vcxproj" .
copy /-Y "%WXHOME%\samples\dragimag\dragimag.vcxproj" .
copy /-Y "%WXHOME%\samples\drawing\drawing.vcxproj" .
copy /-Y "%WXHOME%\samples\dynamic\dynamic.vcxproj" .
copy /-Y "%WXHOME%\samples\erase\erase.vcxproj" .
copy /-Y "%WXHOME%\samples\event\event.vcxproj" .
copy /-Y "%WXHOME%\samples\exec\exec.vcxproj" .
copy /-Y "%WXHOME%\samples\font\font.vcxproj" .
copy /-Y "%WXHOME%\samples\grid\grid.vcxproj" .
copy /-Y "%WXHOME%\samples\help\help.vcxproj" .
copy /-Y "%WXHOME%\samples\html\about\about.vcxproj" .
copy /-Y "%WXHOME%\samples\html\helpview\helpview.vcxproj" .
copy /-Y "%WXHOME%\samples\html\printing\printing.vcxproj" .
copy /-Y "%WXHOME%\samples\html\test\test.vcxproj" .
copy /-Y "%WXHOME%\samples\html\virtual\virtual.vcxproj" .
copy /-Y "%WXHOME%\samples\html\widget\widget.vcxproj" .
copy /-Y "%WXHOME%\samples\html\zip\zip.vcxproj" .
copy /-Y "%WXHOME%\samples\image\image.vcxproj" .
copy /-Y "%WXHOME%\samples\internat\internat.vcxproj" .
copy /-Y "%WXHOME%\samples\ipc\ipc_ipcclient.vcxproj" .
copy /-Y "%WXHOME%\samples\ipc\ipc_ipcserver.vcxproj" .
copy /-Y "%WXHOME%\samples\joytest\joytest.vcxproj" .
copy /-Y "%WXHOME%\samples\layout\layout.vcxproj" .
copy /-Y "%WXHOME%\samples\listctrl\listctrl.vcxproj" .
copy /-Y "%WXHOME%\samples\mdi\mdi.vcxproj" .
copy /-Y "%WXHOME%\samples\mediaplayer\mediaplayer.vcxproj" .
copy /-Y "%WXHOME%\samples\memcheck\memcheck.vcxproj" .
copy /-Y "%WXHOME%\samples\menu\menu.vcxproj" .
copy /-Y "%WXHOME%\samples\mfc\mfc.vcxproj" .
copy /-Y "%WXHOME%\samples\minifram\minifram.vcxproj" .
copy /-Y "%WXHOME%\samples\minimal\minimal.vcxproj" .
copy /-Y "%WXHOME%\samples\nativdlg\nativdlg.vcxproj" .
copy /-Y "%WXHOME%\samples\notebook\notebook.vcxproj" .
copy /-Y "%WXHOME%\samples\oleauto\oleauto.vcxproj" .
copy /-Y "%WXHOME%\samples\opengl\cube\cube.vcxproj" .
copy /-Y "%WXHOME%\samples\opengl\isosurf\isosurf.vcxproj" .
copy /-Y "%WXHOME%\samples\opengl\penguin\penguin.vcxproj" .
copy /-Y "%WXHOME%\samples\ownerdrw\ownerdrw.vcxproj" .
copy /-Y "%WXHOME%\samples\png\png.vcxproj" .
copy /-Y "%WXHOME%\samples\popup\popup.vcxproj" .
copy /-Y "%WXHOME%\samples\propsize\propsize.vcxproj" .
copy /-Y "%WXHOME%\samples\regtest\regtest.vcxproj" .
copy /-Y "%WXHOME%\samples\richtext\richtext.vcxproj" .
copy /-Y "%WXHOME%\samples\rotate\rotate.vcxproj" .
copy /-Y "%WXHOME%\samples\sashtest\sashtest.vcxproj" .
copy /-Y "%WXHOME%\samples\scroll\scroll.vcxproj" .
copy /-Y "%WXHOME%\samples\scrollsub\scrollsub.vcxproj" .
copy /-Y "%WXHOME%\samples\sockets\sockets_client.vcxproj" .
copy /-Y "%WXHOME%\samples\sockets\sockets_server.vcxproj" .
copy /-Y "%WXHOME%\samples\splitter\splitter.vcxproj" .
copy /-Y "%WXHOME%\samples\statbar\statbar.vcxproj" .
copy /-Y "%WXHOME%\samples\taskbar\taskbar.vcxproj" .
copy /-Y "%WXHOME%\samples\text\text.vcxproj" .
copy /-Y "%WXHOME%\samples\thread\thread.vcxproj" .
copy /-Y "%WXHOME%\samples\toolbar\toolbar.vcxproj" .
copy /-Y "%WXHOME%\samples\treectrl\treectrl.vcxproj" .
copy /-Y "%WXHOME%\samples\typetest\typetest.vcxproj" .
copy /-Y "%WXHOME%\samples\validate\validate.vcxproj" .
copy /-Y "%WXHOME%\samples\widgets\widgets.vcxproj" .
copy /-Y "%WXHOME%\samples\wizard\wizard.vcxproj" .
copy /-Y "%WXHOME%\samples\xrc\xrcdemo.vcxproj" .
copy /-Y "%WXHOME%\build\msw\wx.sln" .
copy /-Y "%WXHOME%\samples\samples.sln" .
