diff attributes.h ../../libxslt
diff documents.h ../../libxslt
diff extensions.h ../../libxslt
diff extra.h ../../libxslt
diff functions.h ../../libxslt
diff imports.h ../../libxslt
diff keys.h ../../libxslt
diff libxslt.h ../../libxslt
diff namespaces.h ../../libxslt
diff numbersInternals.h ../../libxslt
diff pattern.h ../../libxslt
diff preproc.h ../../libxslt
diff security.h ../../libxslt
diff templates.h ../../libxslt
diff transform.h ../../libxslt
diff trio.h ../../libxslt
diff triodef.h ../../libxslt
diff variables.h ../../libxslt
diff win32config.h ../../libxslt
diff xslt.h ../../libxslt
diff xsltconfig.h ../../libxslt
diff xsltexports.h ../../libxslt
diff xsltInternals.h ../../libxslt
diff xsltlocale.h ../../libxslt
diff xsltutils.h ../../libxslt
diff xsltwin32config.h ../../libxslt
